apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: staging
      - stage: production
  template:
    metadata:
      name: kargo-demo-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/danielloader/kargo-demo.git
        # Kargo will update this branch to move new commits from the
        # kargo-render branch and/or new images into this stage
        targetRevision: stage/{{stage}}
        path: app
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-{{stage}}
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
