apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

namespace: staging

patches:
- target:
    kind: Ingress
    name: kargo-demo
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: kargo-demo.staging.quotech.company
    - op: replace
      path: /spec/tls/0/hosts/0
      value: kargo-demo.staging.quotech.company
