apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kargo-demo
  namespace: staging
spec:
  ingressClassName: nginx
  rules:
  - host: kargo-demo.staging.quotech.company
    http:
      paths:
      - backend:
          service:
            name: kargo-demo
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kargo-demo.staging.quotech.company
