apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- target:
    kind: Service
    name: kargo-demo
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: kargo-demo.production.quotech.company